"""Emit kernel-metadata.json plus the entry script for one (family, config, fold) job.

The entry script does not contain any training logic. It unpacks the dataset
payload if needed, points the training script's path arguments at the Kaggle
directories, and runs it - so the code that actually trains on Kaggle is the
same file that runs locally, not a fork of it.

One kernel per (model config, fold), so no job approaches Kaggle's 9-hour
session ceiling and a failure costs one fold rather than a sweep.
"""

import argparse
import json
import os

ENTRY_TEMPLATE = '''"""Kaggle entry point for {family} / {config} / {fold_tag}. Generated by 02_make_kernel.py.

Contains no training logic. It unpacks the dataset payload, points the training
script at the Kaggle directories, and runs it unmodified.
"""

import os
import runpy
import shutil
import subprocess
import sys
import zipfile

INPUT_ROOT = "/kaggle/input/{slug}"
WORK_ROOT = "/kaggle/working"
DATA_ROOT = os.path.join(WORK_ROOT, "payload")

FAMILY = "{family}"
SCALOGRAM_CONFIG = "{config}"
PROTOCOL = "{protocol}"
FOLD = {fold}
MAX_EPOCHS = {max_epochs}
VARIANT_TAG = "{variant_tag}"
NEGATIVE_CONTROL = {negative_control}
MANIFEST_SUBDIR = "{manifest_subdir}"


def describe_inputs():
    """Print what is actually mounted. A missing dataset is the single most
    likely reason a kernel dies in the first two seconds, and the default error
    does not say which of the two possible causes it was."""
    if not os.path.isdir("/kaggle/input"):
        print("NOTHING mounted at /kaggle/input")
        return
    for current, directories, files in os.walk("/kaggle/input"):
        if current.count(os.sep) > 5:
            directories[:] = []
            continue
        print("  " + current + " -> dirs=" + str(sorted(directories)[:8]) + " files=" + str(sorted(files)[:8]))


def find_roots_containing(relative_path):
    """Every mounted dataset directory that contains the given relative path.

    Kaggle has mounted datasets at both /kaggle/input/<slug> and
    /kaggle/input/datasets/<owner>/<slug> depending on runtime version, so
    searching for a marker beats hardcoding either. Searching per marker rather
    than once for the whole payload also lets the scalograms and the manifests
    live in DIFFERENT datasets - which is what keeps the 8 GB of ablation
    configs from forcing a re-upload of the 1.4 GB default set.
    """
    found = []
    for current, directories, _ in os.walk("/kaggle/input"):
        if os.path.exists(os.path.join(current, relative_path)):
            found.append(current)
            directories[:] = []
            continue
        # The trees under these are large and cannot contain a top-level marker.
        if os.path.basename(current) in ("scalograms", "manifests", "manifests_negative_control"):
            directories[:] = []
        if current.count(os.sep) > 6:
            directories[:] = []
    found.sort(key=len)
    return found


def find_dataset_root():
    """The dataset holding the training scripts and params.yaml.

    Resolved by looking for scripts/, NOT for scalograms/: once the wavelet
    ablation configs ship as their own dataset, more than one mounted dataset
    contains a scalograms/ directory, and picking by that marker can land on the
    one with no training code in it. Each root is resolved by the marker that
    actually identifies what it is needed for.
    """
    roots = find_roots_containing("scripts")
    if len(roots) == 0:
        roots = find_roots_containing("payload.zip")
    if len(roots) == 0:
        roots = find_roots_containing("scalograms")
    if len(roots) == 0:
        return ""
    return roots[0]


def unpack():
    """The payload may arrive already extracted or still zipped. Handle both."""
    root = find_dataset_root()
    if root == "":
        raise SystemExit(
            "QC FAIL: could not find the dataset anywhere under /kaggle/input.\\n"
            "Either dataset_sources in kernel-metadata.json is wrong, or the dataset "
            "version was still processing when this kernel was pushed. Wait for "
            "`kaggle datasets files <slug>` to list the scalograms, then re-push."
        )
    print("dataset root resolved to " + root)

    archive_path = os.path.join(root, "payload.zip")
    if os.path.isdir(os.path.join(root, "scalograms")):
        print("payload was extracted by Kaggle, using it in place")
        return root
    if os.path.exists(archive_path):
        print("unpacking payload.zip")
        os.makedirs(DATA_ROOT, exist_ok=True)
        with zipfile.ZipFile(archive_path) as archive:
            archive.extractall(DATA_ROOT)
        return DATA_ROOT
    raise SystemExit(
        "QC FAIL: no payload.zip and no scalograms/ under " + root
        + ". Contents: " + str(sorted(os.listdir(root))[:20])
    )


def install_missing():
    """Kaggle's image has torch, numpy, pandas and sklearn but not mlflow.

    This is why enable_internet must be true in kernel-metadata.json. Installed
    with --no-warn-conflicts so a harmless version note does not look like a
    failure in the log.
    """
    needed = []
    for module_name, package in [("mlflow", "mlflow"), ("dotenv", "python-dotenv")]:
        try:
            __import__(module_name)
        except ImportError:
            needed.append(package)

    if len(needed) == 0:
        print("all required packages already present")
        return

    print("installing: " + str(needed))
    result = subprocess.run(
        [sys.executable, "-m", "pip", "install", "-q", "--no-warn-conflicts"] + needed,
        capture_output=True, text=True,
    )
    print("pip exit code: " + str(result.returncode))
    if result.returncode != 0:
        print(result.stdout[-2000:])
        print(result.stderr[-2000:])
        raise SystemExit("QC FAIL: pip install failed inside the kernel")


def seed_checkpoints(models_dir):
    """Copy previously trained checkpoints into the working models directory.

    warm_start_fusion initialises each branch from the ecg_only and pcg_only
    checkpoints FOR THE SAME FOLD, but /kaggle/working is empty at the start of
    every kernel - resume state does not survive between kernel invocations. So
    those checkpoints are shipped as a second Kaggle dataset and copied in here
    before training starts.
    """
    source = ""
    for current, directories, files in os.walk("/kaggle/input"):
        if "ecg_only" in directories and "pcg_only" in directories:
            source = current
            break
        if current.count(os.sep) > 6:
            directories[:] = []
    if source == "":
        print("no checkpoint dataset found under /kaggle/input")
        return False

    print("seeding checkpoints from " + source)
    copied = 0
    for current, _, files in os.walk(source):
        for name in files:
            if not name.endswith(".pth"):
                continue
            relative = os.path.relpath(os.path.join(current, name), source)
            destination = os.path.join(models_dir, relative)
            os.makedirs(os.path.dirname(destination), exist_ok=True)
            shutil.copy2(os.path.join(current, name), destination)
            copied = copied + 1
    print("seeded " + str(copied) + " checkpoints")
    return copied > 0


def main():
    print("=== kaggle entry: {family} {config} {fold_tag} ===")
    print("torch sees cuda:", __import__("torch").cuda.is_available())
    describe_inputs()
    install_missing()
    data_root = unpack()

    models_dir = os.path.join(WORK_ROOT, "models")
    reports_dir = os.path.join(WORK_ROOT, "reports")
    tracking_dir = os.path.join(models_dir, "mlflow_tracking")
    os.makedirs(tracking_dir, exist_ok=True)
    os.makedirs(reports_dir, exist_ok=True)

    os.environ["MLFLOW_TRACKING_URI"] = "file:" + tracking_dir
    os.environ["MLFLOW_ALLOW_FILE_STORE"] = "true"
    os.environ["MLFLOW_EXPERIMENT_NAME"] = "ecg-pcg-fusion"
    os.environ["MLFLOW_DISABLE_AGENT_HINT"] = "1"

    if FAMILY == "warm_start_fusion" and not seed_checkpoints(models_dir):
        raise SystemExit(
            "QC FAIL: warm_start_fusion needs the ecg_only and pcg_only checkpoints "
            "for this fold, and no checkpoint dataset is attached. Sync them with "
            "01_sync_dataset.py --checkpoints-only and pass --extra-dataset."
        )

    script = os.path.join(data_root, "scripts", "modeling", FAMILY, "01_train.py")
    if not os.path.exists(script):
        raise SystemExit("QC FAIL: training script not found at " + script)

    # The config's scalograms and the manifests may live in different datasets.
    scalogram_roots = find_roots_containing(os.path.join("scalograms", SCALOGRAM_CONFIG))
    if len(scalogram_roots) == 0:
        if os.path.isdir(os.path.join(data_root, "scalograms", SCALOGRAM_CONFIG)):
            scalogram_roots = [data_root]
        else:
            raise SystemExit(
                "QC FAIL: no mounted dataset contains scalograms/" + SCALOGRAM_CONFIG
            )
    scalogram_root = os.path.join(scalogram_roots[0], "scalograms")
    print("scalograms resolved to " + scalogram_root)

    manifest_roots = find_roots_containing(MANIFEST_SUBDIR)
    if len(manifest_roots) == 0:
        if os.path.isdir(os.path.join(data_root, MANIFEST_SUBDIR)):
            manifest_roots = [data_root]
        else:
            raise SystemExit("QC FAIL: no mounted dataset contains " + MANIFEST_SUBDIR)
    manifest_root = os.path.join(manifest_roots[0], MANIFEST_SUBDIR)
    print("manifests resolved to " + manifest_root)

    argv = [
        script,
        "--protocol", PROTOCOL,
        "--fold", str(FOLD),
        "--scalogram-config", SCALOGRAM_CONFIG,
        "--scalogram-root", scalogram_root,
        "--manifest-root", manifest_root,
        "--model-root", models_dir,
        "--report-root", reports_dir,
        "--params", os.path.join(data_root, "params.yaml"),
        "--max-epochs", str(MAX_EPOCHS),
    ]
    if VARIANT_TAG:
        argv = argv + ["--variant-tag", VARIANT_TAG]
    if NEGATIVE_CONTROL:
        argv = argv + ["--negative-control"]

    print("argv:", argv)
    sys.argv = argv
    runpy.run_path(script, run_name="__main__")

    # Kaggle returns /kaggle/working as the kernel output. Drop the payload copy
    # so the download is results only, not a second copy of the dataset.
    if DATA_ROOT != INPUT_ROOT:
        shutil.rmtree(DATA_ROOT, ignore_errors=True)
    print("entry script done")


main()
'''


def kernel_slug(family, config, fold_tag, variant_tag):
    parts = ["ecgpcg", family.replace("_", "-"), config.replace("_", "-"), fold_tag.replace("_", "-")]
    if variant_tag:
        parts.append(variant_tag.strip("_").replace("_", "-"))
    return "-".join(parts).lower()


def main():
    parser = argparse.ArgumentParser(description="generate a Kaggle kernel for one training job")
    parser.add_argument("--family", required=True)
    parser.add_argument("--scalogram-config", default="default")
    parser.add_argument("--protocol", default="cv", choices=["dev", "cv"])
    parser.add_argument("--fold", type=int, default=0)
    parser.add_argument("--max-epochs", type=int, default=50)
    parser.add_argument("--variant-tag", default="")
    parser.add_argument("--negative-control", action="store_true")
    parser.add_argument("--username", default=os.environ.get("KAGGLE_USERNAME", ""))
    parser.add_argument("--dataset-slug", default=os.environ.get("KAGGLE_DATASET_SLUG", "ecg-pcg-fusion-scalograms"))
    parser.add_argument("--manifest-subdir", default="manifests",
                        help="manifest directory inside the dataset; the negative-control "
                             "arms use manifests_negative_control/arm_<x>")
    parser.add_argument("--extra-dataset", default="",
                        help="second dataset slug to attach, e.g. the unimodal checkpoints")
    parser.add_argument("--output-dir", default=".kaggle_kernels")
    args = parser.parse_args()

    if args.username == "":
        raise SystemExit("QC FAIL: no Kaggle username. Set KAGGLE_USERNAME in .env or pass --username")

    fold_tag = "dev" if args.protocol == "dev" else "cv_fold" + str(args.fold)
    slug = kernel_slug(args.family, args.scalogram_config, fold_tag, args.variant_tag)
    job_dir = os.path.join(args.output_dir, slug)
    os.makedirs(job_dir, exist_ok=True)

    print("=== 02_make_kernel ===")
    print(f"family={args.family} config={args.scalogram_config} protocol={args.protocol} fold_tag={fold_tag}")
    print(f"kernel slug={slug}")

    entry = ENTRY_TEMPLATE.format(
        family=args.family,
        config=args.scalogram_config,
        protocol=args.protocol,
        fold=args.fold,
        fold_tag=fold_tag,
        slug=args.dataset_slug,
        max_epochs=args.max_epochs,
        variant_tag=args.variant_tag,
        negative_control=str(bool(args.negative_control)),
        manifest_subdir=args.manifest_subdir,
    )
    entry_path = os.path.join(job_dir, "run.py")
    with open(entry_path, "w", newline="\n") as handle:
        handle.write(entry)

    dataset_sources = [args.username + "/" + args.dataset_slug]
    if args.extra_dataset:
        dataset_sources.append(args.username + "/" + args.extra_dataset)

    metadata = {
        "id": args.username + "/" + slug,
        "title": slug,
        "code_file": "run.py",
        "language": "python",
        "kernel_type": "script",
        "is_private": "true",
        "enable_gpu": "true",
        "enable_internet": "true",
        # NvidiaTeslaP100 is not usable with the default Kaggle image because of
        # PyTorch compatibility - Kaggle's own docs warn about this.
        "machine_shape": "NvidiaTeslaT4",
        "dataset_sources": dataset_sources,
        "competition_sources": [],
        "kernel_sources": [],
    }
    metadata_path = os.path.join(job_dir, "kernel-metadata.json")
    with open(metadata_path, "w") as handle:
        json.dump(metadata, handle, indent=2)

    print(f"wrote {entry_path} and {metadata_path}")
    print(f"push it with: python scripts/remote/03_run_kernel.py --job-dir {job_dir}")


if __name__ == "__main__":
    main()
